version: '3.5'
services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: 'my_books'
      MYSQL_USER: 'milad'
      MYSQL_PASSWORD: 'my-secret-pw'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
